#!/bin/sh

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"

#Setting the string of NaN in case there is a problem.
numVars="15"
result="";
for i in $(seq 1 $numVars) ; do 
    result="NaN $result" ; 
done 


if [ -f $baseT1/T1_first/T1_first_all_fast_firstseg.nii.gz ] ; then
    result=`${FSLDIR}/bin/fslstats $baseT1/T1_first/T1_first_all_fast_firstseg -H 58 0.5 58.5 | sed 's/\.000000//g' | awk 'BEGIN { ORS = " " } { print }'| awk '{print $10 " " $49 " " $11 " " $50 " " $12 " " $51 " " $13 " " $52 " " $17 " " $53 " " $18 " " $54 " " $26 " " $58 " " $16 }' `
fi

mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result
    
cd $origDir


